TurismoRealWeb/Controllers/ArriendoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TurismoRealWeb.BLL;
using System.Web.Security;


namespace TurismoRealWeb.Controllers
{
    [Authorize]
    public class ArriendoController : Controller
    {
        // GET: Arriendo
        public ActionResult Index()
        {
            ViewBag.arriendos = new Arriendo().ReadAll();
            return View();
        }

        // GET: Arriendo/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult Buscar(string texto)
        {
            if (texto != null)
            {
                ViewBag.arriendos = new Arriendo().BuscarPorCliente(texto);
                return View();                
            }

            ViewBag.arriendos = new Arriendo().ReadAll();
            return View();
        }


        // GET: Arriendo/Create
        public ActionResult Create(int id)
        {
            if (Session["id"] != null)
            {
                Arriendo arriendo = new Arriendo();
                arriendo.Departamento = new Departamento().Find(id);
                arriendo.ClienteId = (decimal)Session["id"];
                arriendo.total_serv = 0;
                arriendo.DptoId = arriendo.Departamento.Id;
                arriendo.Total = arriendo.Departamento.Precio;
                return View(arriendo);
            }

            else
            {
                FormsAuthentication.SignOut();
                Session.Abandon();
                Session.RemoveAll();
                return RedirectToAction("Departamentos");
            }

        }       

        private void EnviarCiudades()
        {
            ViewBag.ciudades = new Ciudad().ReadAll();
        }

        private void EnviarDptos()
        {
            ViewBag.departamentos = new Departamento().ReadAll();            
        }

        // POST: Arriendo/Create
        [HttpPost]
        public ActionResult Create(Arriendo arriendo)
        {            
            try
            {
                // TODO: Add insert logic here
                if (!ModelState.IsValid)
                {
                    return View(arriendo);
                }                
                arriendo.Save();
                TempData["SuccessMessage"] = arriendo.Departamento.Nombre + "  Reservado Correctamente";
                return RedirectToAction("Reserva", "Sitio");
            }
            catch
            {
                return View(arriendo);
            }
        }

        // GET: Arriendo/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Arriendo/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                //TempData["SuccessMessage"];
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Arriendo/Delete/5
        public ActionResult Delete(int id)
        {
            if (new Arriendo().Find(id) == null)
            {
                TempData["SuccessMessage"] = "No existe el departamento";
                return RedirectToAction("Index");
            }


            if (new Arriendo().Delete(id))
            {
                TempData["SuccessMessage"] = "Eliminado Correctamente";
                return RedirectToAction("Index");
            }


            TempData["SuccessMessage"] = "No se ha podido eliminar";
            return RedirectToAction("Index");            
        }

        // POST: Arriendo/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here                
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public  ActionResult RecibirPago(decimal id)
        {
            Arriendo arri = new Arriendo().Find(id);
            arri.Total = 4 * arri.Total / 5;
            arri.FecIni.ToShortDateString();
            arri.FecFin.ToShortDateString();
            return View(arri);
        }

        [HttpPost]
        public ActionResult RecibirPago(Arriendo arriendo)
        {
            arriendo.Check_In();
            TempData["SuccessMessage"] = "Pago Recibido Correctamente";
            return RedirectToAction("Index");
        }
               
                

        public ActionResult CheckOut(int id)
        {
            if (new Arriendo().Find(id) == null)
            {
                TempData["SuccessMessage"] = "No existe el arriendo";
                return RedirectToAction("Index");
            }


            if (new Arriendo().Check_Out(id))
            {
                TempData["SuccessMessage"] = "Check-Out Correcto";
                return RedirectToAction("Index");
            }


            TempData["SuccessMessage"] = "No se ha podido realizar Check-Out";
            return RedirectToAction("Index");
        }
                
    }
}
//TempData["SuccessMessage"]

TurismoRealWeb/Controllers/DepartamentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TurismoRealWeb.BLL;

namespace TurismoRealWeb.Controllers
{
    [Authorize]
    public class DepartamentoController : Controller
    {
        // GET: Departamento
        public ActionResult Index()
        {
            ViewBag.departamentos = new Departamento().ReadAll();

            EnviarCiudades();
            return View();
        }


        // GET: Departamento/Details/5
        public ActionResult Details(int id)
        {
            Departamento dpto = new Departamento().Find(id);
            EnviarCiudades();
            return View(dpto);
        }

        [HttpGet]
        public JsonResult ListarDptos()
        {
            List<Departamento> oList = new List<Departamento>();

            oList = new Departamento().ReadAll();

            return Json(new { data = oList }, JsonRequestBehavior.AllowGet);
        }

        // GET: Departamento/Create
        public ActionResult Create()
        {
            EnviarCiudades();
            return View();
        }
        
        private void EnviarCiudades()
        {
            ViewBag.ciudades = new Ciudad().ReadAll();
        }

        // POST: Departamento/Create
        [HttpPost]
        public ActionResult Create(Departamento departamento)
        {
            try
            {
                // TODO: Add insert logic here
                if (!ModelState.IsValid)
                {
                    EnviarCiudades();
                    return View(departamento);
                }

                departamento.Save();
                TempData["SuccessMessage"] = departamento.Nombre + "  Guardado Correctamente";
                return RedirectToAction("Index");
            }
            catch
            {
                return View(departamento);
            }
        }

        // GET: Departamento/Edit/5
        public ActionResult Edit(int id)
        {
            Departamento d = new Departamento().Find(id);

            if(d == null)
            {
                TempData["SuccessMessage"] = "El Departamento no existe";
                return RedirectToAction("Index");
            }

            if (d.Disponible == "1")
            {                
                d.IsDisp = true;
            }
            else
            {
                d.IsDisp = false;
            }
            
            EnviarCiudades();
            return View(d);
        }

        // POST: Departamento/Edit/5
        [HttpPost]
        public ActionResult Edit( Departamento departamento)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    EnviarCiudades();
                    return View(departamento);
                }
                // TODO: Add update logic here
                departamento.Update();                                               
                TempData["SuccessMessage"] = departamento.Nombre + "  Modificado Correctamente";
                return RedirectToAction("Index");
            }
            catch
            {
                return View(departamento);
            }
        }

        // GET: Departamento/Delete/5
        public ActionResult Delete(int id)
        {
            if(new Departamento().Find(id) == null)
            {
                TempData["SuccessMessage"] = "No existe el departamento";
                return RedirectToAction("Index");
            }


            if(new Departamento().Delete(id))
            {
                TempData["SuccessMessage"] = "Eliminado Correctamente";
                return RedirectToAction("Index");
            }


            TempData["SuccessMessage"] = "No se ha podido eliminar";
            return RedirectToAction("Index");
        }

        // POST: Departamento/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TurismoRealWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TurismoRealWeb.BLL;

namespace TurismoRealWeb.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public ActionResult Home()
        {
            ViewBag.arriendos = new Arriendo().ReadAll();
            return View("Index");
        }


        public ActionResult Index()
        {
            ViewBag.arriendos = new Arriendo().ReadAll();
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }        
    }
}

TurismoRealWeb/Controllers/MantencionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TurismoRealWeb.BLL;

namespace TurismoRealWeb.Controllers
{
    [Authorize]
    public class MantencionController : Controller
    {
        // GET: Mantencion
        public ActionResult Index()
        {
            ViewBag.mantencion = new Mantencion().ReadAll();
            return View();
        }

        // GET: Mantencion/Details/5
        public ActionResult Details(int id)
        {
            Mantencion manten = new Mantencion().Find(id);
            EnviarDptos();
            return View(manten);
        }

        // GET: Mantencion/Create
        public ActionResult Create()
        {
            

            EnviarDptos();
            return View();
        }

        private void EnviarDptos()
        {
            ViewBag.departamentos = new Departamento().ReadAll();
        }

        // POST: Mantencion/Create
        [HttpPost]
        public ActionResult Create( Mantencion mantencion)
        {
            try
            {
                // TODO: Add insert logic here
                if (!ModelState.IsValid)
                {
                    EnviarDptos();
                    return View(mantencion);
                }

                mantencion.Save();
                TempData["SuccessMessage"] = "Mantención Creada Correctamente";

                return RedirectToAction("Index");
            }
            catch
            {
                return View(mantencion);
            }
        }

        // GET: Mantencion/Edit/5
        public ActionResult Edit(int id)
        {
            Mantencion man = new Mantencion().Find(id);

            if (man == null)
            {
                TempData["SuccessMessage"] = "La Mantención no existe";
                return RedirectToAction("Index");
            }

            //man.Fech_ini = DateTime.MinValue;
            //man.Fech_term = DateTime.MinValue;            

            EnviarDptos();
            return View(man);
        }

        // POST: Mantencion/Edit/5
        [HttpPost]
        public ActionResult Edit( Mantencion mantencion)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    EnviarDptos();
                    return View(mantencion);

                }
                // TODO: Add update logic here
                mantencion.Update();
                TempData["SuccessMessage"] = "Mantención modificada correctamente";
                return RedirectToAction("Index");
            }
            catch
            {
                return View(mantencion);
            }
        }

        // GET: Mantencion/Delete/5
        public ActionResult Delete(int id)
        {
            if (new Mantencion().Find(id) == null)
            {
                TempData["SuccessMessage"] = "Mantención no existe";
                return RedirectToAction("Index");
            }

            if (new Mantencion().Delete(id))
            {
                TempData["SuccessMessage"] = "Mantención eliminada Correctamente";
                return RedirectToAction("Index");
            }

            TempData["SuccessMessage"] = "No se ha podido Eliminar";
            return RedirectToAction("Index");
        }

        // POST: Mantencion/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TurismoRealWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TurismoRealWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TurismoRealWeb/Views/Home/Index.cshtml
@using TurismoRealWeb.BLL;

@{
    ViewBag.Title = "Home";
}


<h1 class="mt-4">Bienvenido @User.Identity.Name</h1>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Panel de Control</li>
</ol>

<div class="row">
    <div class="col-xl-3 col-md-6">
        <div class="card bg-primary text-white mb-4">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-9">
                        <h6 style="font-size:larger">Estadias</h6>
                    </div>
                    <div class="col-sm-3">
                        <i class="fas fa-bed fa-3x"></i>
                    </div>
                </div>
            </div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" href="@Url.Action("Index","Arriendo")">Administrar</a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-warning text-white mb-4">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-9">
                        <h6 style="font-size:larger">Disponibilidad</h6>
                    </div>
                    <div class="col-sm-3">
                        <i class="fas fa-building fa-3x"></i>
                    </div>
                </div>
            </div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" href="@Url.Action("Index","Departamento")">Administrar</a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-success text-white mb-4">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-9">
                        <h6 style="font-size:larger">Mantención</h6>
                    </div>
                    <div class="col-sm-3">
                        <i class="fas fa-cogs fa-3x"></i>
                    </div>
                </div>
            </div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" href="@Url.Action("Index","Mantencion")">Administrar</a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-danger text-white mb-4">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-9">
                        <h6 style="font-size:larger">Administración de Ingresos</h6>
                    </div>
                    <div class="col-sm-3">
                        <i class="fas fa-money-bill-alt fa-3x"></i>
                    </div>
                </div>
            </div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" href="">Administrar</a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-info text-white mb-4">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-9">
                        <h6 style="font-size:larger">Servicios Extra</h6>
                    </div>
                    <div class="col-sm-3">
                        <i class="fas fa-concierge-bell fa-3x"></i>
                    </div>
                </div>
            </div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" href="@Url.Action("Index","Servicios")">Administrar</a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
</div>


@{ List<Arriendo> arriendos = (List<Arriendo>)ViewBag.arriendos;}

<div class="card mb-4" >
    <div class="card-header">
        <i class="fas fa-list me-1"></i>
        Historial de Arriendos
    </div>
    <div class="card-body">
        <div>
            <table id="tabla" class="table table-hover table-striped table-bordered" style="width: 100%">
                <tr>
                    <th>Id</th>
                    <th>Cliente</th>
                    <th>Fecha Entrada</th>
                    <th>Fecha Salida</th>

                </tr>
                @foreach (var arriendo in arriendos)
                {
                    <tr>
                        <td>@arriendo.Id</td>
                        <td>@arriendo.Cliente.Nombre @arriendo.Cliente.Paterno @arriendo.Cliente.Materno</td>
                        <td>@arriendo.FecIni.ToShortDateString()</td>
                        <td>@arriendo.FecFin.ToShortDateString()</td>
                    </tr>
                }

            </table>

        </div>
    </div>
</div>

@*<br />

    <div class="jumbotron">
        <h1>Turismo Real</h1>
        <p class="lead">Los mejores departamentos al mejor precio.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
    </div>

    <div class="row">
        <div class="col-md-4">
            <h2>Dedicados a ti</h2>
            <p>
                Elige los mejores departamentos para tus vacaciones.
            </p>
            <br />
            <br />
            <p><a class="btn btn-default" href="">Revisa Nuestros Departamentos &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Experimenta Zonas de Chile</h2>
            <p>Contamos con hospedajes en principales puntos turísticos del país.</p>
            <p><a class="btn btn-default" href="">Revisa Zonas de Servicio &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Tours a tu medida</h2>
            <p>Cada Departamento ofrece tours pensados para tu disfute.</p>
            <br />
            <br />
            <p><a class="btn btn-default" href="">Oferta de Tours &raquo;</a></p>
        </div>
    </div>*@