TurismoRealWeb/Controllers/DepartamentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TurismoRealWeb.BLL;

namespace TurismoRealWeb.Controllers
{
    [Authorize]
    public class DepartamentoController : Controller
    {
        // GET: Departamento
        public ActionResult Index()
        {
            ViewBag.departamentos = new Departamento().ReadAll();

            EnviarCiudades();
            return View();
        }


        // GET: Departamento/Details/5
        public ActionResult Details(int id)
        {
            Departamento dpto = new Departamento().Find(id);
            EnviarCiudades();
            return View(dpto);
        }

        [HttpGet]
        public JsonResult ListarDptos()
        {
            List<Departamento> oList = new List<Departamento>();

            oList = new Departamento().ReadAll();

            return Json(new { data = oList }, JsonRequestBehavior.AllowGet);
        }

        // GET: Departamento/Create
        public ActionResult Create()
        {
            EnviarCiudades();
            return View();
        }
        
        private void EnviarCiudades()
        {
            ViewBag.ciudades = new Ciudad().ReadAll();
        }

        // POST: Departamento/Create
        [HttpPost]
        public ActionResult Create(Departamento departamento)
        {
            try
            {
                // TODO: Add insert logic here
                if (!ModelState.IsValid)
                {
                    EnviarCiudades();
                    return View(departamento);
                }

                departamento.Save();
                TempData["SuccessMessage"] = departamento.Nombre + "  Guardado Correctamente";
                return RedirectToAction("Index");
            }
            catch
            {
                return View(departamento);
            }
        }

        // GET: Departamento/Edit/5
        public ActionResult Edit(int id)
        {
            Departamento d = new Departamento().Find(id);

            if(d == null)
            {
                TempData["SuccessMessage"] = "El Departamento no existe";
                return RedirectToAction("Index");
            }

            if (d.Disponible == "1")
            {                
                d.IsDisp = true;
            }
            else
            {
                d.IsDisp = false;
            }
            
            EnviarCiudades();
            return View(d);
        }

        // POST: Departamento/Edit/5
        [HttpPost]
        public ActionResult Edit( Departamento departamento)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    EnviarCiudades();
                    return View(departamento);
                }
                // TODO: Add update logic here
                departamento.Update();                                               
                TempData["SuccessMessage"] = departamento.Nombre + "  Modificado Correctamente";
                return RedirectToAction("Index");
            }
            catch
            {
                return View(departamento);
            }
        }

        // GET: Departamento/Delete/5
        public ActionResult Delete(int id)
        {
            if(new Departamento().Find(id) == null)
            {
                TempData["SuccessMessage"] = "No existe el departamento";
                return RedirectToAction("Index");
            }


            if(new Departamento().Delete(id))
            {
                TempData["SuccessMessage"] = "Eliminado Correctamente";
                return RedirectToAction("Index");
            }


            TempData["SuccessMessage"] = "No se ha podido eliminar";
            return RedirectToAction("Index");
        }

        // POST: Departamento/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TurismoRealWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TurismoRealWeb.BLL;

namespace TurismoRealWeb.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public ActionResult Home()
        {
            ViewBag.arriendos = new Arriendo().ReadAll();
            return View("Index");
        }


        public ActionResult Index()
        {
            ViewBag.arriendos = new Arriendo().ReadAll();
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }        
    }
}

TurismoRealWeb/Controllers/ReservaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TurismoRealWeb.Controllers
{
    public class ReservaController : Controller
    {
        // GET: Reserva
        public ActionResult Index()
        {
            return View();
        }

        // GET: Reserva/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Reserva/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Reserva/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Reserva/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Reserva/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Reserva/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Reserva/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TurismoRealWeb/Controllers/SitioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using TurismoRealWeb.BLL;

namespace TurismoRealWeb.Controllers
{
    public class SitioController : Controller
    {

        // GET: Sitio
        public ActionResult Home()
        {
            ViewBag.departamentos = new Departamento().ReadAll();

            EnviarCiudades();
            return View();
        }

        public ActionResult Departamentos()
        {
            ViewBag.departamentos = new Departamento().ReadAll();

            EnviarCiudades();
            return View();
        }

        private void EnviarCiudades()
        {
            ViewBag.ciudades = new Ciudad().ReadAll();
        }

        [Authorize]
        public ActionResult Reserva()
        {

            if (Session["id"] != null)
            {
                decimal userId = (decimal)Session["id"];
                ViewBag.arriendos = new Arriendo().ArriendosPorUser(userId);
                return View();
            }
            else
            {
                FormsAuthentication.SignOut();
                Session.Abandon();
                Session.RemoveAll();
                return RedirectToAction("Departamentos");
            }
        }

        [HttpPost]
        public ActionResult Reserva(Arriendo arriendo)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    EnviarCiudades();
                    return View(arriendo);
                }
                // TODO: Add update logic here
                arriendo.Update();
                TempData["SuccessMessage"] = arriendo.Nombre + "  Reservado Correctamente";
                return RedirectToAction("Index");
            }
            catch
            {
                return View(arriendo);
            }
        }


        public ActionResult ConfirmReserva(int id)
        {
            Reserva reserva = new Reserva();
            reserva.Arriendo = new Arriendo().Find(id);
            reserva.ArriendoId = reserva.Arriendo.Id;
            reserva.NomPersona = reserva.Arriendo.Cliente.Nombre + " " + reserva.Arriendo.Cliente.Paterno + " " + reserva.Arriendo.Cliente.Materno;
            reserva.Valor = 2 * reserva.Arriendo.Total / 10;
            reserva.Fech = DateTime.Today;
            reserva.Fech.ToShortDateString();
            reserva.Acomp = 0;
            return View(reserva);
        }

        [HttpPost]
        public ActionResult ConfirmReserva(Reserva reserva)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(reserva);
                }

                reserva.Save();
                TempData["SuccessMessage"] = "Pago Realizado Correctamente";
                return RedirectToAction("Reserva");
            }
            catch
            {
                return View(reserva);
            }

        }

        public ActionResult Delete(int id)
        {
            if (new Reserva().Find(id) == null)
            {
                TempData["SuccessMessage"] = "Reserva no existe";
                return RedirectToAction("Reserva");
            }


            if (new Reserva().Cancelar(id))
            {
                TempData["SuccessMessage"] = "Reserva Cancelada Correctamente";
                return RedirectToAction("Reserva");
            }


            TempData["SuccessMessage"] = "No se ha podido cancelar";
            return RedirectToAction("Reserva");
        }

        [Authorize]
        public ActionResult Servicios(int id)
        {
            Servicio_Contratado servs = new Servicio_Contratado();
            servs.Arriendo = new Arriendo().Find(id);
            servs.ArriendoId = servs.Arriendo.Id;
            ViewBag.Servicios = new Servicio().ReadAll();

            return View(servs);
        }

        [HttpPost]
        public ActionResult Servicios(Servicio_Contratado servicio_Contratado)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    ViewBag.Servicios = new Servicio().ReadAll();
                    return View(servicio_Contratado);
                }
                Servicio servicio = new Servicio().Find(servicio_Contratado.ServicioId);
                servicio_Contratado.Costo = servicio.Costo;
                servicio_Contratado.Realizado = "0";
                servicio_Contratado.PostChk = "0";

                servicio_Contratado.Save();
                TempData["SuccessMessage"] = "Servicios Contratados Satisfactoriamente";
                return RedirectToAction("Reserva");
            }
            catch
            {
                return View(servicio_Contratado);
            }
        }

        [Authorize]
        public ActionResult CancelarReserva(int id)
        {
            if (new Reserva().Find(id) == null)
            {
                TempData["SuccessMessage"] = "Reserva no existe";
                return RedirectToAction("Reserva");
            }


            if (new Reserva().Cancelar(id))
            {
                TempData["SuccessMessage"] = "Reserva Cancelada Correctamente";
                return RedirectToAction("Reserva");
            }


            TempData["SuccessMessage"] = "No se ha podido cancelar la Reserva";
            return RedirectToAction("Reserva");
        }

        [Authorize]
        public ActionResult Transporte(int id) 
        {
            Transporte trans = new Transporte();
            trans.Arriendo = new Arriendo().Find(id);
            trans.ArriendoId = trans.Arriendo.Id;
            trans.Costo = 20000;
            return View(trans);
        }


        [HttpPost]
        public ActionResult Transporte(Transporte transporte)
        {
            try
            {
                if (!ModelState.IsValid)
                {                    
                    return View();
                }                
                
                transporte.Save();
                TempData["SuccessMessage"] = "Solicitud de Transporte Creada Satisfactoriamente";
                return RedirectToAction("Reserva");
            }
            catch
            {
                return View();
            }
        }



    }
}

TurismoRealWeb/Views/Sitio/ConfirmReserva.cshtml
@model TurismoRealWeb.BLL.Reserva

@{
    ViewBag.Title = "Arriendo";
    Layout = "~/Views/Shared/_LayoutUsuario.cshtml";
}

<h2></h2>


<!--Detalle Depa-->
<!DOCTYPE html>
<html>
<head>
    <title>Reserva Arriendo</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <style>
        html, body {
            min-height: 100%;
            background-image: url('../../Img/hotel-wallpaper.png');
        }

        body, div, form, input, select, textarea, label {
            padding: 0;
            margin: 0;
            outline: none;
            font-family: Roboto, Arial, sans-serif;
            font-size: 14px;
            color: #666;
            line-height: 22px;
        }

        h1 {
            position: absolute;
            margin: 0;
            font-size: 50px;
            color: #fff;
            z-index: 2;
            line-height: 83px;
        }

        legend {
            padding: 10px;
            font-family: Roboto, Arial, sans-serif;
            font-size: 18px;
            color: #fff;
            background-color: #006622;
        }

        textarea {
            width: calc(100% - 12px);
            padding: 5px;
        }

        .testbox {
            display: flex;
            justify-content: center;
            align-items: center;
            height: inherit;
            padding: 20px;
        }

        form {
            width: 100%;
            padding: 20px;
            border-radius: 6px;
            background: #fff;
            box-shadow: 0 0 8px #ff6a00;
        }

        .banner {
            position: relative;
            height: 250px;
            background-image: url("https://interrailero.com/wp-content/uploads/2019/10/que-ver-en-chile-turismo.jpg");
            background-size: cover;
            display: flex;
            justify-content: center;
            align-items: center;
            text-align: center;
        }

            .banner::after {
                content: "";
                background-color: rgba(0, 0, 0, 0.4);
                position: absolute;
                width: 100%;
                height: 100%;
            }



        textarea {
            width: calc(100% - 12px);
            padding: 5px;
        }

        .item:hover p, .item:hover i, .question:hover p, .question label:hover, input:hover::placeholder {
            color: #006622;
        }

        .item input:hover, .item select:hover, .item textarea:hover {
            border: 1px solid transparent;
            box-shadow: 0 0 3px 0 #006622;
            color: #006622;
        }

        .item {
            position: relative;
            margin: 10px 0;
        }

            .item span {
                color: red;
            }


            .item i, input[type="date"]::-webkit-calendar-picker-indicator {
                position: absolute;
                font-size: 20px;
                color: #00b33c;
            }

            .item i {
                right: 1%;
                top: 30px;
                z-index: 1;
            }

        .week {
            display: flex;
            justify-content: space-between;
        }

        .columns {
            display: flex;
            justify-content: space-between;
            flex-direction: row;
            flex-wrap: wrap;
        }

            .columns div {
                width: 48%;
            }


        input[type=radio], input[type=checkbox] {
            display: none;
        }

        label.radio {
            position: relative;
            display: inline-block;
            margin: 5px 20px 15px 0;
            cursor: pointer;
        }

        .question span {
            margin-left: 30px;
        }

        .question-answer label {
            display: block;
        }

        label.radio:before {
            content: "";
            position: absolute;
            left: 0;
            width: 17px;
            height: 17px;
            border-radius: 50%;
            border: 2px solid #ccc;
        }

        label.radio:after {
            content: "";
            position: absolute;
            top: 6px;
            left: 5px;
            width: 8px;
            height: 4px;
            border: 3px solid #006622;
            border-top: none;
            border-right: none;
            transform: rotate(-45deg);
            opacity: 0;
        }


        .flax {
            display: flex;
            justify-content: space-around;
        }

        .btn-block {
            margin-top: 10px;
            text-align: center;
        }

        button {
            width: 150px;
            padding: 10px;
            border: none;
            border-radius: 5px;
            background: #006622;
            font-size: 16px;
            color: #fff;
            cursor: pointer;
        }

            button:hover {
                background: #00b33c;
            }

        .name-item input, .name-item div {
            width: calc(50% - 20px);
        }

            .name-item div input {
                width: 97%;
            }

            .name-item div label {
                display: block;
                padding-bottom: 5px;
            }
        }
    </style>
</head>
<body>
    <div class="testbox">
        <div style="flex">
            <div class="banner">
                <h1>Confirmar Reserva</h1>
            </div>
            <br />
            @using (Html.BeginForm("ConfirmReserva", "Sitio"))
            {
                @Html.ValidationSummary()
                <a>Detalles de Arriendo</a>
                <div class="columns">
                    @Html.HiddenFor(reserva => reserva.ArriendoId)
                    @Html.HiddenFor(reserva => reserva.Fech)
                    <div class="item form-floating col-10">
                        @Html.TextBoxFor(reserva => reserva.NomPersona, new { @placeholder = "Solicitante", @class = "form-control", @readonly = "true" })
                        <label for="Nombre">Solicitante</label>
                    </div>
                    <div class="item form-floating col-10">
                        @Html.TextBoxFor(reserva => reserva.Valor, new { @placeholder = "Precio", @class = "form-control", @readonly = "true" })
                        <label for="Precio">Valor Reserva</label>
                    </div>
                    <div class="item form-floating col-10">
                        @Html.TextBoxFor(reserva => reserva.Acomp, new { @class = "form-control", placeholder = "Acompañantes" })
                        <label for="FecFin">N° Acompañantes</label>
                    </div>
                </div>
                <div class="row" style="margin-top:12px;text-align:center;">
                    <button type="submit" value="Guardar" class="btn btn-primary">Continuar a WebPay</button>
                </div>

            }
            <br />
            @Html.ActionLink("Volver", "Reserva","Sitio", null, new { btn5 = "back", @class = "btn btn-danger" })
        </div>
    </div>
</body>
</html>

TurismoRealWeb/Views/Sitio/Departamentos.cshtml
@using TurismoRealWeb.BLL;

@{
    ViewBag.Title = "Departamentos";
    Layout = "~/Views/Shared/_LayoutUsuario.cshtml";
}


<!--Listado-->
@{ List<Departamento> departamentos = (List<Departamento>)ViewBag.departamentos;}



<body style="background-image: url('../../Img/hotel-wallpaper.png')">
    <div class="d-grid mb-5 mt-2 ">
        <div class="row row-cols-1 row-cols-md-3 g-5">

            @if (departamentos != null)
            {
                foreach (var dpto in departamentos)
                {
                    <div class="col">
                        <div class="card">
                            <img src="https://imgclasificados3.emol.com/Proyectos/imagenes//PR_FOTO_4484_1.jpg" class="card-img-top" alt="...">
                            <div class="card-body">
                                <h5 class="card-title">@dpto.Nombre</h5>
                                <p class="card-text">@dpto.Ciudad.Nombre</p>
                                <p class="card-text"><small>@Html.DisplayFor(modelItem => dpto.Precio)</small></p>
                                @*@if (dpto.Disponible == "1")
                                {
                                  <span class="badge rounded-pill text-bg-primary">Disponible</span>
                                }
                                else
                                {
                                    <p>@(dpto.Disponible == "1" ? "Disponible": "No Disponible")</p>
                                }*@
                                
                                
                                <a class="btn btn-primary" href="@Url.Action("Create","Arriendo", new { id = dpto.Id })">Reserva</a>
                            </div>
                        </div>
                    </div>
                }

            }
        </div>
    </div>
</body>

TurismoRealWeb/Views/Sitio/Reserva.cshtml
@using TurismoRealWeb.BLL
@{
    ViewBag.Title = "Arriendos";
    Layout = "~/Views/Shared/_LayoutUsuario.cshtml";
}

<h2>Tus Reservas </h2>


@{ List<Arriendo> arriendos = (List<Arriendo>)ViewBag.arriendos; }





<!DOCTYPE html>
<div>
    <table id="tabla" class="table table-hover table-striped table-bordered" style="width: 100%">
        <tr>
            <th>N° Arriendo</th>
            <th>Nombre</th>
            <th>Departamento</th>
            <th>Fecha Entrada</th>
            <th>Fecha Salida</th>
            <th>Estado</th>
            <th>Reserva</th>
            <th>Valor Arriendo</th>
            <th>Valor Servicios</th>
            <th>Contratar</th>

        </tr>
        @foreach (var arriendo in arriendos)
        {
    <tr>
        <td>@arriendo.Id</td>
        <td>@arriendo.Cliente.Nombre  @arriendo.Cliente.Paterno @arriendo.Cliente.Materno</td>
        <td>@arriendo.Departamento.Nombre</td>
        <td>@arriendo.FecIni.ToShortDateString()</td>
        <td>@arriendo.FecFin.ToShortDateString()</td>
        <td>@(arriendo.CheckIn == "3" ? "Pago Pendiente": "Reserva Pagada")</td>
        @if (arriendo.Checkout == "1")
        {
            <td>@(arriendo.Checkout == "1" ? "Terminada" : "Activa")</td>
        }
        else
        {
            <td>@(arriendo.Checkout == "3" ? "Cancelada" : "Activa")</td>
            
        }

        <td>@Html.DisplayFor(x => arriendo.Total)</td>
        <td>@Html.DisplayFor(x => arriendo.total_serv)</td>
        <td>
            @if (arriendo.CheckIn == "3")
            {
                <button class="btn btn-success btn-sm-2" onclick="location.href='@Url.Action("ConfirmReserva","Sitio", new { id = arriendo.Id })'"><i class="fas fa-check"></i> Pagar Reserva</button>
            }

            @if (arriendo.Checkout == "0")
            {
                <button class="btn btn-warning btn-sm-2" onclick="location.href='@Url.Action("Servicios","Sitio", new { id = arriendo.Id })'"><i class="fas fa-concierge-bell"></i> Contratar Servicio</button>
                <button class="btn btn-info btn-sm-2" onclick="location.href='@Url.Action("Transporte","Sitio", new { id = arriendo.Id })'"><i class="fas fa-taxi"></i> Solicitar Transporte</button>
                <a class="btn btn-danger btn-sm-2" href="@Url.Action("CancelarReserva", "Sitio", new { id = arriendo.Id })" onclick="return confirm('Está seguro que quiere cancelar su reserva?')"><i class="fas fa-close"></i> Cancelar Reserva</a>
            }
            @if (arriendo.Checkout == "3")
            {
        <div style="color:red"> Reserva Cancelada</div>
            }

        </td>
    </tr>
        }

    </table>
</div>
@section scripts{
    <script type="text/javascript">

        function openSuccessModal(strMessage) {
            var myDiv = document.getElementById("myModalSuccessAlertBody");
            myDiv.innerHTML = strMessage;

            $('#myModalSuccess').modal("show");
        }


        $(document).ready(function () {
            var msg = "@TempData["SuccessMessage"]";
            if (msg)
                openSuccessModal(msg);
        });



    </script>
}

TurismoRealWeb/Views/Sitio/Servicios.cshtml
@model TurismoRealWeb.BLL.Servicio_Contratado

@{
    ViewBag.Title = "Contratar Servicios";
    Layout = "~/Views/Shared/_LayoutUsuario.cshtml";
}

<h2>Contrata Servicios para tu Arriendo</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4></h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(Servicio_Contratado => Servicio_Contratado.ArriendoId)
    <h4>Tabla de Precios</h4>
    
        <table id="tabla" class="table table-hover table-bordered" style="width: 20%">
            <tr>
                <th>Servicio</th>
                <th>Valor</th>
            </tr>
            @foreach (var servicio in ViewBag.Servicios)
            { 
                <tr>
                    <td>@servicio.Descripcion</td>
                    <td>$@servicio.Costo</td>
                </tr>
            }

        </table>
    
    <div class="row" style="width: 20%">
        <div class="form-floating mb-3" style="padding:10px">
            @Html.DropDownListFor(Servicio_Contratado => Servicio_Contratado.ServicioId, new SelectList(ViewBag.Servicios, "Id", "Descripcion"), new { @placeholder = "Servicio", @class = "form-control" })
            <label for="FecIni">Servicio</label>
        </div>
    </div>


    <div class="form-group" style="width: 20%">
        @Html.EditorFor(Servicio_Contratado => Servicio_Contratado.Fecha, new { htmlAttributes = new { @class = "form-control", placeholder = "Fecha de Servicio", @readonly = "true" } })
        <label for="FecIni">Fecha a Contratar</label>
    </div>

    <br />
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Continuar a WebPay" class="btn btn-warning" />
        </div>
    </div>
</div>
}
<br />
<div>
    @Html.ActionLink("Volver", "Reserva", null, new { btn5 = "back", @class = "btn btn-danger" })
</div>

@section Scripts {    
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/css")

    <script type="text/javascript">
        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                dateFormat: "dd/mm/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-10:+10",
                minDate: new Date()
            });

        });
    </script>
}

TurismoRealWeb/Views/Sitio/Transporte.cshtml
@model TurismoRealWeb.BLL.Transporte

@{
    ViewBag.Title = "Contratar Transporte";
    Layout = "~/Views/Shared/_LayoutUsuario.cshtml";
}

<h2>Solicitar Transporte</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4></h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(transporte => transporte.ArriendoId)


    <div class="form-floating  mb-3" style="width: 20%">
        @Html.TextBoxFor(transporte => transporte.Origen, new { @placeholder = "Departamento", @class = "form-control" })
        <label for="Origen">Dirección Origen</label>
    </div>

    <div class="form-floating  mb-3" style="width: 20%">
        @Html.TextBoxFor(transporte => transporte.Destino, new { @placeholder = "Departamento", @class = "form-control" })
        <label for="Destino">Dirección Destino</label>
    </div>

    <div class="form-floating  mb-3" style="width: 20%">
        @Html.EditorFor(transporte => transporte.Fecha, new { htmlAttributes = new { @class = "form-control", placeholder = "Fecha", @readonly = "true" } })
        <label for="FecIni">Fecha de Traslado </label>
    </div>

    <div class="form-floating  mb-3" style="width: 20%">
        @Html.TextBoxFor(transporte => transporte.Pasajeros, new { @placeholder = "Departamento", @class = "form-control" })
        <label for="Pasajeros">N° Pasajeros</label>
    </div>

    <div class="form-floating  mb-3" style="width: 20%">
        @Html.TextBoxFor(transporte => transporte.Costo, new { @placeholder = "Departamento", @class = "form-control", @readonly = "true" })
        <label for="Pasajeros">Costo</label>
    </div>

    <div class=" mb-3" style="width: 20%">
        <label for="Sentido">Sentido</label>
        <div class="form-check" style="width: 60%">
            @Html.RadioButtonFor(transporte => transporte.Sentido, "IDA") PARTIDA <br />
            @Html.RadioButtonFor(transporte => transporte.Sentido, "VUELTA") REGRESO
        </div>

    </div>

    <br />
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Solicitar" class="btn btn-warning" />
            @Html.ActionLink("Volver", "Reserva", null, new { btn5 = "back", @class = "btn btn-danger" })
        </div>
        <br />
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/css")

    <script type="text/javascript">
        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                dateFormat: "dd/mm/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-10:+10",
                minDate: new Date()
            });

        });
    </script>
}