TurismoRealWeb/Controllers/InventarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TurismoRealWeb.BLL;

namespace TurismoRealWeb.Controllers
{
    [Authorize]
    public class InventarioController : Controller
    {
        // GET: Inventario
        public ActionResult Index()
        {
            ViewBag.inventarios = new Inventario().ReadAll();

            EnviarDptos();
            return View();
        }

        // GET: Inventario/Details/5
        public ActionResult Details(int id)
        {
            Inventario inven = new Inventario().Find(id);
            EnviarDptos();
            return View(inven);
        }

        // GET: Inventario/Create
        public ActionResult Create()
        {
            EnviarDptos();
            return View();
        }

        private void EnviarDptos()
        {
            ViewBag.departamentos = new Departamento().ReadAll();
        }

        // POST: Inventario/Create
        [HttpPost]
        public ActionResult Create( Inventario inventario)
        {
            try
            {
                // TODO: Add insert logic here
                if (!ModelState.IsValid)
                {
                    EnviarDptos();
                    return View(inventario);
                }

                inventario.Save();
                TempData["SuccessMessage"] = inventario.Item + " Guardado Correctamente";
                
                return RedirectToAction("Index");
            }
            catch
            {
                return View(inventario);
            }
        }

        // GET: Inventario/Edit/5
        public ActionResult Edit(int id)
        {
            Inventario inv = new Inventario().Find(id);

            if (inv == null)
            {
                TempData["SuccessMessage"] = "El Objeto no existe";
                return RedirectToAction("Index");
            }

            if (inv.Disponible == "1")
            {
                inv.IsDisp = true;
            }
            else
            {
                inv.IsDisp = false;
            }

            EnviarDptos();
            return View(inv);
        }

        // POST: Inventario/Edit/5
        [HttpPost]
        public ActionResult Edit( Inventario inventario)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    EnviarDptos();
                    return View(inventario);
                }
                // TODO: Add update logic here
                inventario.Update();
                TempData["SuccessMessage"] = inventario.Item +" Modificado Correctamente";
                return RedirectToAction("Index");
            }
            catch
            {
                return View(inventario);
            }
        }

        // GET: Inventario/Delete/5
        public ActionResult Delete(int id)
        {
            if (new Inventario().Find(id) == null)
            {
                TempData["SuccessMessage"] = "No existe el Objeto";
                return RedirectToAction("Index");
            }


            if (new Inventario().Delete(id))
            {
                TempData["SuccessMessage"] = "Eliminado Correctamente";
                return RedirectToAction("Index");
            }


            TempData["SuccessMessage"] = "No se ha podido eliminar";
            return RedirectToAction("Index");
        }

        // POST: Inventario/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TurismoRealWeb/Views/Inventario/Create.cshtml
@model TurismoRealWeb.BLL.Inventario
@{
    ViewBag.Title = "Create";
}

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery-ui-1.13.2.min.js"></script>
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

@section scripts{
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/css")

    <script type="text/javascript">
        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                dateFormat: "dd/mm/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-10:+10",
            });

        });
    </script>

}

<div class="card-body">
    <div class="row">
        <div class="col-12">
            <button type="button" class="btn btn-success" onclick="location.href ='@Url.Action("Index", "Inventario")'">Inventario de Departamentos</button>
        </div>
    </div>
    <div class="card col-md-5" style="margin: 20px 20px; width: 500px; height: 600px; ">
        @using (Html.BeginForm())
        {
            <h3 class="card-header" style="text-align:center;">Nuevo Item de Departamento</h3>
            <div class="card-body" style="width:60%; margin:0 auto;padding:20px;">
                @Html.ValidationSummary()

                <div class="row">
                    <div class="form-floating mb-3" style="padding:10px">
                        @Html.LabelFor(i => i.Item)
                    </div>
                    <div class="form-floating mb-3" style="padding:10px">
                        @Html.TextBoxFor(i => i.Item)
                    </div>
                </div>
                <div class="row">
                    <div class="form-floating mb-3" style="padding:10px">
                        @Html.LabelFor(i => i.Dpto)
                    </div>
                    <div class="form-floating mb-3" style="padding:10px">
                        @Html.DropDownListFor(i => i.DptoId, new SelectList(ViewBag.departamentos, "Id", "Nombre"))
                    </div>
                </div>
                <div class="row">
                    <div class="form-floating mb-3" style="padding:10px">
                        @Html.LabelFor(i => i.Valor)
                    </div>
                    <div class="form-floating mb-3" style="padding:10px">
                        @Html.TextBoxFor(i => i.Valor)
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6" style="padding:10px">
                        @Html.LabelFor(i => i.FechComp)
                    </div>
                    <div class="col-md-6" style="padding:10px">
                        @Html.EditorFor(i => i.FechComp, new { htmlAttributes = new { @class = "form-control", placeholder = "Fecha de Compra ", @readonly = "true" } })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6" style="padding:10px">
                        @Html.LabelFor(d => d.Disponible)
                    </div>
                    <div class="col-md-6" style="padding:10px">
                        @Html.CheckBoxFor(d => d.IsDisp)
                    </div>
                </div>



                <br />
                <div class="row" style="margin-top:12px;text-align:center;">
                    <button type="submit" value="Guardar" class="btn btn-primary">Guardar</button>
                </div>
            </div>
        }
    </div>
</div>

TurismoRealWeb/Views/Inventario/Details.cshtml
@model TurismoRealWeb.BLL.Inventario

@{
    ViewBag.Title = "Detalles";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Inventario</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.DptoId)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.DptoId)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Item)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Item)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Valor)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Valor)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Disponible)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Disponible)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.FechComp)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.FechComp)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Modificar", "Edit", new { id = Model.Id }, new { btn1 = "edit", @class = "btn btn-secondary" })
        @Html.ActionLink("Volver", "Index", null, new { btn5 = "back", @class = "btn btn-danger" })
    </p>
</body>
</html>

TurismoRealWeb/Views/Inventario/Edit.cshtml
@model TurismoRealWeb.BLL.Inventario
@{
    ViewBag.Title = "Edit";
}
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery-ui-1.13.2.min.js"></script>
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

@section scripts{
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/css")

    <script type="text/javascript">
        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                dateFormat: "dd/mm/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-10:+10",
            });

        });
    </script>

}

<div class="card-body">
    <div class="row">
        <div class="col-12">
            <button type="button" class="btn btn-success" onclick="location.href ='@Url.Action("Index", "Inventario")'">Inventario de Departamentos</button>
        </div>
    </div>
    <div class="col-md-5" style="margin: 20px 20px; width: 700px; height: 600px; background-color: #f2f2f2 ">
        @using (Html.BeginForm())
        {
            <h3 style="text-align:center;">Nuevo Item de Departamento</h3>
            <div style="width:60%; margin:0 auto;padding:20px;">
                @Html.ValidationSummary()
                @Html.HiddenFor(i => i.Id)
                <div class="row">
                    <div class="col-md-6" style="padding:10px">
                        @Html.LabelFor(i => i.Item)
                    </div>
                    <div class="col-md-6" style="padding:10px">
                        @Html.TextBoxFor(i => i.Item)
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6" style="padding:10px">
                        @Html.LabelFor(i => i.Dpto)
                    </div>
                    <div class="col-md-6" style="padding:10px">
                        @Html.DropDownListFor(i => i.DptoId, new SelectList(ViewBag.departamentos, "Id", "Nombre"))
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6" style="padding:10px">
                        @Html.LabelFor(i => i.Valor)
                    </div>
                    <div class="col-md-6" style="padding:10px">
                        @Html.TextBoxFor(i => i.Valor)
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6" style="padding:10px">
                        @Html.LabelFor(i => i.FechComp)
                    </div>
                    <div class="col-md-6" style="padding:10px">
                        @Html.EditorFor(i => i.FechComp, new { htmlAttributes = new { @class = "form-control", placeholder = "Fecha de Compra ", @readonly = "true" } })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6" style="padding:10px">
                        @Html.LabelFor(d => d.Disponible)
                    </div>
                    <div class="col-md-6" style="padding:10px">
                        @Html.CheckBoxFor(d => d.IsDisp)
                    </div>
                </div>

                <br />
                <div class="row" style="margin-top:12px;text-align:center;">
                    <button type="submit" value="Modificar" class="btn btn-primary">Submit</button>
                </div>
            </div>
        }
    </div>
</div>

TurismoRealWeb/Views/Inventario/Index.cshtml
@using TurismoRealWeb.BLL;

@{
    ViewBag.Title = "Index";
}


@{ List<Inventario> inventarios = (List<Inventario>)ViewBag.inventarios;}


<div class="table-responsive card mb-4 mt-4 bg-">
    <div class="card-header bg-dark" style="color: white">
        <i class="fas fa-building me-1 "></i> Lista de Inventario
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <button type="button" class="btn btn-success" onclick="location.href ='@Url.Action("Create", "Inventario")'">Crear Departamento</button>
            </div>
        </div>

        <hr />
        <table id="tabla" class="table table-hover table-striped" style="width: 100%">
            <tr>
                <th>Item</th>
                <th>Valor</th>
                <th>Departamento</th>
                <th>Disponible</th>
                <th>Fecha de Compra</th>
                <th>Opciones</th>

            </tr>
            @foreach (var inventario in inventarios)
            {
        <tr>
            <td>@inventario.Item</td>
            <td>@inventario.Valor</td>
            <td>@inventario.Dpto.Nombre</td>
            <td>@(inventario.Disponible == "1" ? "Disponible":"No Disponible")</td>
            <td>@inventario.FechComp.ToShortDateString()</td>
            <td>
                <button class="btn btn-warning btn-sm-2" onclick="location.href='@Url.Action("Details","Inventario", new { id = inventario.Id })'"><i class="fas fa-search"></i></button>
                <button class="btn btn-success btn-sm-2" onclick="location.href='@Url.Action("Edit","Inventario", new { id = inventario.Id })'"><i class="fas fa-pen"></i></button>
                <a class="btn btn-danger btn-sm-2" href="@Url.Action("Delete", "Inventario", new { id = inventario.Id })" onclick="return confirm('Está seguro de eliminar este registro?')"><i class="fas fa-trash"></i></a>

            </td>
        </tr>
            }

        </table>
    </div>
</div>

@section scripts{
    <script type="text/javascript">

        function openSuccessModal(strMessage) {
            var myDiv = document.getElementById("myModalSuccessAlertBody");
            myDiv.innerHTML = strMessage;

            $('#myModalSuccess').modal("show");
        }


        $(document).ready(function () {
            var msg = "@TempData["SuccessMessage"]";
            if (msg)
                openSuccessModal(msg);
        });



    </script>
}