TurismoRealWeb/Controllers/ArriendoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TurismoRealWeb.BLL;
using System.Web.Security;


namespace TurismoRealWeb.Controllers
{
    [Authorize]
    public class ArriendoController : Controller
    {
        // GET: Arriendo
        public ActionResult Index()
        {
            ViewBag.arriendos = new Arriendo().ReadAll();
            return View();
        }

        // GET: Arriendo/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult Buscar(string texto)
        {
            if (texto != null)
            {
                ViewBag.arriendos = new Arriendo().BuscarPorCliente(texto);
                return View();                
            }

            ViewBag.arriendos = new Arriendo().ReadAll();
            return View();
        }


        // GET: Arriendo/Create
        public ActionResult Create(int id)
        {
            if (Session["id"] != null)
            {
                Arriendo arriendo = new Arriendo();
                arriendo.Departamento = new Departamento().Find(id);
                arriendo.ClienteId = (decimal)Session["id"];
                arriendo.total_serv = 0;
                arriendo.DptoId = arriendo.Departamento.Id;
                arriendo.Total = arriendo.Departamento.Precio;
                return View(arriendo);
            }

            else
            {
                FormsAuthentication.SignOut();
                Session.Abandon();
                Session.RemoveAll();
                return RedirectToAction("Departamentos");
            }

        }       

        private void EnviarCiudades()
        {
            ViewBag.ciudades = new Ciudad().ReadAll();
        }

        private void EnviarDptos()
        {
            ViewBag.departamentos = new Departamento().ReadAll();            
        }

        // POST: Arriendo/Create
        [HttpPost]
        public ActionResult Create(Arriendo arriendo)
        {            
            try
            {
                // TODO: Add insert logic here
                if (!ModelState.IsValid)
                {
                    return View(arriendo);
                }                
                arriendo.Save();
                TempData["SuccessMessage"] = arriendo.Departamento.Nombre + "  Reservado Correctamente";
                return RedirectToAction("Reserva", "Sitio");
            }
            catch
            {
                return View(arriendo);
            }
        }

        // GET: Arriendo/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Arriendo/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                //TempData["SuccessMessage"];
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Arriendo/Delete/5
        public ActionResult Delete(int id)
        {
            if (new Arriendo().Find(id) == null)
            {
                TempData["SuccessMessage"] = "No existe el departamento";
                return RedirectToAction("Index");
            }


            if (new Arriendo().Delete(id))
            {
                TempData["SuccessMessage"] = "Eliminado Correctamente";
                return RedirectToAction("Index");
            }


            TempData["SuccessMessage"] = "No se ha podido eliminar";
            return RedirectToAction("Index");            
        }

        // POST: Arriendo/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here                
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public  ActionResult RecibirPago(decimal id)
        {
            Arriendo arri = new Arriendo().Find(id);
            arri.Total = 4 * arri.Total / 5;
            arri.FecIni.ToShortDateString();
            arri.FecFin.ToShortDateString();
            return View(arri);
        }

        [HttpPost]
        public ActionResult RecibirPago(Arriendo arriendo)
        {
            arriendo.Check_In();
            TempData["SuccessMessage"] = "Pago Recibido Correctamente";
            return RedirectToAction("Index");
        }
               
                

        public ActionResult CheckOut(int id)
        {
            if (new Arriendo().Find(id) == null)
            {
                TempData["SuccessMessage"] = "No existe el arriendo";
                return RedirectToAction("Index");
            }


            if (new Arriendo().Check_Out(id))
            {
                TempData["SuccessMessage"] = "Check-Out Correcto";
                return RedirectToAction("Index");
            }


            TempData["SuccessMessage"] = "No se ha podido realizar Check-Out";
            return RedirectToAction("Index");
        }
                
    }
}
//TempData["SuccessMessage"]

TurismoRealWeb/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TurismoRealWeb.BLL;
using System.Web.Security;

namespace TurismoRealWeb.Controllers
{
    public class AuthController : Controller
    {
        public ActionResult Login()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Login(Usuario usuario, string ReturnUrl)
        {
            Session["User"] = null;
            Session["id"] = null;
            Session["username"] = null;
            if (IsValid(usuario))
            {
                
                FormsAuthentication.SetAuthCookie(usuario.Username, false);

                if (ReturnUrl != null)
                {
                    usuario = usuario.Buscar(usuario.Username);
                    Session["User"] = usuario;
                    Session["id"] = usuario.Id;
                    Session["username"] = usuario.Username;

                    return Redirect(ReturnUrl);
                }
                usuario = usuario.Buscar(usuario.Username);
                Session["User"] = usuario;
                Session["id"] = usuario.Id;
                Session["username"] = usuario.Username;

                if (usuario.Id_tipo == 1)
                {
                    return RedirectToAction("Home", "Sitio");
                }
                return RedirectToAction("Index", "Home");
                
            }
            TempData["mensaje"] = "Usuario o Contraseña Incorrectos";
            return View(usuario);
        }



        private bool IsValid(Usuario usuario)
        {
            if (usuario.Password != null)
            {
                usuario.Password = TR_Recursos.ConvertirSha256(usuario.Password);
                return usuario.Autenticar();
            }
            else
            {
                return false;
            }
        }

        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            Session.RemoveAll();
            return RedirectToAction("Home", "Sitio");
        }

        public ActionResult LogOut2()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            Session.RemoveAll();
            return RedirectToAction("Home", "Sitio");
        }

        public ActionResult Registro()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Registro(Usuario usuario)
        {
            try
            {
                if (!ModelState.IsValid)
                {                    
                    return View(usuario);
                }
                FormsAuthentication.SetAuthCookie(usuario.Username, false);
                usuario.Password = TR_Recursos.ConvertirSha256(usuario.Password);
                usuario.Id_tipo = 1;

                // TODO: Add insert logic here
                usuario.Reg();

                usuario = usuario.Buscar(usuario.Username);
                Session["User"] = usuario;
                Session["id"] = usuario.Id;
                Session["username"] = usuario.Username;


                TempData["mensaje"] = "Registrado Correctamente";

                return RedirectToAction("Home", "Sitio");
            }
            catch
            {
                return View(usuario);
            }
        }


    }
}

TurismoRealWeb/Controllers/ReservaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TurismoRealWeb.Controllers
{
    public class ReservaController : Controller
    {
        // GET: Reserva
        public ActionResult Index()
        {
            return View();
        }

        // GET: Reserva/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Reserva/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Reserva/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Reserva/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Reserva/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Reserva/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Reserva/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TurismoRealWeb/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TurismoRealWeb.BLL;

namespace TurismoRealWeb.Controllers
{
    [Authorize]
    public class UsuarioController : Controller
    {
        // GET: Usuario
        public ActionResult Index()
        {
            ViewBag.usuarios = new Usuario().ReadAll();
            return View();
        }

        // GET: Usuario/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Usuario/Create
        public ActionResult Create()
        {
            EnviarTipos();
            return View();
        }

        private void EnviarTipos()
        {
            ViewBag.tipos_user = new Tipo_usuario().ReadAll();
        }

        // POST: Usuario/Create
        [HttpPost]
        public ActionResult Create(Usuario usuario)
        {
            try
            {
                // TODO: Add insert logic here
                usuario.Save();
                TempData["mensaje"] = "Guardado Correctamente";
                return RedirectToAction("Index");
            }
            catch
            {
                return View(usuario);
            }
        }

        // GET: Usuario/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Usuario/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Usuario/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Usuario/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TurismoRealWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Turismo Real</title>
    @Styles.Render("~/Content/css")
    @*@Scripts.Render("~/bundles/modernizr")*@    
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="@Url.Action("Index","Home")">Turismo Real</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        @*<form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>*@
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto me-0 me-md-3 my-2 my-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i>@User.Identity.Name</a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    @*<li><a class="dropdown-item" href="#!">Settings</a></li>
                    <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                    <li><hr class="dropdown-divider" /></li>*@
                    <li><a class="dropdown-item" href="@Url.Action("LogOut", "Auth")">Cerrar Sesión</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Resumen</div>
                        <a class="nav-link" href="@Url.Action("Index","Home")">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        <a class="nav-link" href="@Url.Action("Index","Usuario")">
                            <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                            Usuarios
                        </a>
                        <div class="sb-sidenav-menu-heading">Mantenedores</div>
                        <a class="nav-link" href="@Url.Action("Index","Departamento")">
                            <div class="sb-nav-link-icon"><i class="fas fa-building"></i></div>
                            Departamentos
                        </a>
                        <a class="nav-link" @*href="@Url.Action("Index","Reserva")"*@>
                            <div class="sb-nav-link-icon"><i class="fas fa-bookmark"></i></div>
                            Reservas
                        </a>
                        <a class="nav-link" href="@Url.Action("Index","Arriendo")">
                            <div class="sb-nav-link-icon"><i class="fas fa-address-book"></i></div>
                            Arriendos
                        </a>
                        <a class="nav-link" @*href="@Url.Action("Index","Servicio")"*@>
                            <div class="sb-nav-link-icon"><i class="fas fa-concierge-bell"></i></div>
                            Servicios
                        </a>
                        <a class="nav-link" href="@Url.Action("Index","Mantencion")">
                            <div class="sb-nav-link-icon"><i class="fas fa-cogs"></i></div>
                            Mantenciones
                        </a>
                        <a class="nav-link" href="@Url.Action("Index","Inventario")">
                            <div class="sb-nav-link-icon"><i class="fas fa-clipboard-list"></i></div>
                            Inventario
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">                    
                    <div class="small">Sesión Iniciada como:</div>
                    @User.Identity.Name
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">


                    <!--Success Dialog Start-->
                    <div id="myModalSuccess" class="modal fade fa-text-width: 30%;" tabindex="-1" role="dialog">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h2 class="modal-title">Correcto!</h2>
                                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div id="myModalSuccessAlertBody" class="modal-body alert alert-success">
                                    This is a modal body. our msessage will appear here.
                                </div>
                                <div class="modal-footer">
                                    &nbsp;
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--Success Dialog End-->
                    <!--Failure Dialog Start-->
                    @*<div id="myModalFailure" class="modal fade fa-text-width: 30%;" tabindex="-1" role="dialog">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h2 class="modal-title">Error!</h2>
                                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div id="myModalFailureAlertBody" class="modal-body alert alert-danger">
                                    This is a modal body. our msessage will appear here.
                                </div>
                                <div class="modal-footer">
                                    &nbsp;
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>*@
                    <!--Failure Dialog End-->


                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Turismo Real 2022</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>


    @*@User.Identity.Name
        @if (User.Identity.IsAuthenticated)
        {
            <li class:"log">
                <a href="#">@User.Identity.Name</a>
            </li>
            <li class:"log">
                @Html.ActionLink("Cerrar Sesión", "LogOut", "Auth")
            </li>
        }
        else
        {
            <li class:"log">
                @Html.ActionLink("Iniciar Sesión", "Login", "Auth")
            </li>
        }*@
    
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/complementos")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @RenderSection("scripts2", required: false)
</body>
</html>

TurismoRealWeb/Views/Shared/_LayoutUsuario.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Turismo Real</title>
    @Styles.Render("~/Content/css")
    <link href="~/Content/css/styles.css" rel="stylesheet" />
    <link rel="icon" type="image/x-icon" href="~/Img/assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
</head>
<body >
    <!-- Navigation-->
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark" id="mainNav">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="@Url.Action("Home","Sitio")">Turismo Real</a>        
        <!-- Navbar Search-->
        @*<form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                    <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
                </div>
            </form>*@
        <!-- Navbar-->
    <ul class="navbar-nav ms-auto me-0 me-md-3 my-2 my-md-0">
        @if (User.Identity.IsAuthenticated)
        {
            <li><a class="nav-link" href="@Url.Action("Reserva", "Sitio")">Tus Arriendos</a></li>
        }        
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i>@User.Identity.Name</a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                @if (User.Identity.IsAuthenticated)
                {
                    <li><a class="dropdown-item" href="@Url.Action("LogOut2", "Auth")">Cerrar Sesion</a></li>
                }
                else
                {
                    <li ><a class="dropdown-item" href="@Url.Action("Login","Auth")">Inicia Sesion</a></li>
                    <li ><a class="dropdown-item" href="@Url.Action("Registro","Auth")">Registrate</a></li>
                }
            </ul>
        </li>
    </ul>
    </nav>

<div id="layoutSidenav" >
    <div id="layoutSidenav_nav">        
            <nav class="sb-sidenav accordion sb-sidenav-light" style="background-image: url('../../Img/hotel-wallpaper.png')" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    @*<div class="nav">
                        <div class="sb-sidenav-menu-heading">Resumen</div>
                        <a class="nav-link" href="@Url.Action("Index","Home")">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        <a class="nav-link" href="@Url.Action("Index","Usuario")">
                            <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                            Usuarios
                        </a>
                        <div class="sb-sidenav-menu-heading">Mantenedores</div>
                        <a class="nav-link" href="@Url.Action("Index","Departamento")">
                            <div class="sb-nav-link-icon"><i class="fas fa-building"></i></div>
                            Departamentos
                        </a>
                        <a class="nav-link" href="@Url.Action("Index","Reserva")">
                            <div class="sb-nav-link-icon"><i class="fas fa-bookmark"></i></div>
                            Reservas
                        </a>
                        <a class="nav-link" href="@Url.Action("Index","Arriendo")">
                            <div class="sb-nav-link-icon"><i class="fas fa-address-book"></i></div>
                            Arriendos
                        </a>
                        <a class="nav-link" href="@Url.Action("Index","Servicio")">
                            <div class="sb-nav-link-icon"><i class="fas fa-concierge-bell"></i></div>
                            Servicios
                        </a>
                        <a class="nav-link" href="@Url.Action("Index","Mantencion")">
                            <div class="sb-nav-link-icon"><i class="fas fa-cogs"></i></div>
                            Mantenciones
                        </a>
                        <a class="nav-link" href="@Url.Action("Index","Inventario")">
                            <div class="sb-nav-link-icon"><i class="fas fa-clipboard-list"></i></div>
                            Inventario
                        </a>
                    </div>*@
                </div>
            </nav>        
    </div>
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid px-4">
                <div id="myModalSuccess" class="modal fade fa-text-width: 30%;" tabindex="-1" role="dialog">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h2 class="modal-title">Correcto!</h2>
                                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div id="myModalSuccessAlertBody" class="modal-body alert alert-success">
                                This is a modal body. our msessage will appear here.
                            </div>
                            <div class="modal-footer">
                                &nbsp;
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>

                @RenderBody()
            </div>
        </main>
    </div>
</div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/complementos")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>